spring.datasource.url=jdbc:postgresql://ep-muddy-bonus-ac038z13-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ThcNk1DQtdE4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=false
# logging.level.org.hibernate.SQL=OFF
# gemini.api.key=AQ.Ab8RN6Kcw7o1zaE2Vdtxf71QrwtQom8FhJW0QszmeULPRLNREg
gemini.api.key=AQ.Ab8RN6K_YKpK5bVTQ6ieXU4GXGbzI4QXD4XXVgTCyhQCCYdxFQ
server.servlet.context-path=/api
