# database
spring.datasource.url=jdbc:postgresql://ep-muddy-bonus-ac038z13-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ThcNk1DQtdE4
spring.datasource.driver-class-name=org.postgresql.Driver

# settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# usar env.properties (n tem mais)
# spring.config.import=optional:file:.env.properties

# log de query 
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF

# path pra api
server.servlet.context-path=/api

