spring.datasource.url=jdbc:postgresql://ep-muddy-bonus-ac038z13-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ThcNk1DQtdE4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=false
# logging.level.org.hibernate.SQL=OFF
# gemini.api.key=AQ.Ab8RN6LmlI5nayoPHRP9b5bqu8-vHuu_4ZtsJR-SQqKkAjoQrw
gemini.api.key=AQ.Ab8RN6J20XB79b5Ju-H8Fokrpm5waSSpFJPQH9kXvT6Zo8dCBQ